const AlgorithmsTitleEnum = {
  ASTAR: "A* Search",
  DIJKSTRA: "Dijkstra",
  GREEDY_BREATH_FIRST_SEARCH: "Greedy Breath First Search",
  BREATH_FIRST_SEARCH: "Breath First Search",
  BREATH_FIRST_SEARCH_BIDIRECTIONAL: "Bidirectional Breath First Search",
  DEPTH_FIRST_SEARCH: "Depth First Search",
  SWARM: "Swarm",
  CONVERGENT_SWARM: "Convergent Swarm",
  QUICK_SORT: "Quick Sort",
  MERGE_SORT: "Merge Sort",
  HEAP_SORT: "Heap Sort",
  SHELL_SORT: "Shell Sort",
  BUBBLE_SORT: "Bubble Sort",
  SELECTION_SORT: "Selection Sort",
  INSERTION_SORT: "Insertion Sort",
  GNOME_SORT: "Gnome Sort",
  SHAKER_SORT: "Shaker Sort",
  ODD_EVEN_SORT: "Odd-Even Sort",
  PANCAKE_SORT: "Pancake Sort",
  RADIX_SORT: "Radix Sort",
  CYCLE_SORT: "Cycle Sort",
  BITONIC_SORT: "Bitonic Sort",
  TIM_SORT: "Tim Sort",
  CUBE_SORT: "Cube Sort",
  BOGO_SORT: "Bogo Sort",
  BST_PREORDER: "Binary Search Tree Preorder Traversal",
  BST_POSTORDER: "Binary Search Tree Postorder Traversal",
  BST_INORDER: "Binary Search Tree Inorder Traversal",
  SIEV: "Sieve of Eratosthenes",
 
};

export default AlgorithmsTitleEnum;
