
const DescriptionEnum = {

    ALGORITHM_TEXT: "E-AlgoViz is an interactive Algorithm Visualizer E-learning tool designed to simplify complex algorithms and enhance the learning experience.Dive into the world of algorithms, explore various data structures, and witness the algorithms come to life.Accelerate your algorithmic knowledge and unlock the power of problem-solving with E-AlgoViz.",
    PATHFINDING_ALGORITHM_TEXT: "Unlock the power of pathfinding algorithms with the immersive Pathfinding Algorithm Visualizer. Experience real-time execution, dynamic updates, and informative visuals, bridging the gap between theory and practice. Perfect for developers, researchers, and enthusiasts.",
    SORTING_ALGORITHM_TEXT: "Embark on a transformative journey through the world of sorting algorithms with our cutting-edge Sorting Algorithm Visualizer. Immerse yourself in the realm of computational efficiency as you witness the intricacies of real-time executionand visually captivating representations. Tailored for tutors, students, and algorithm aficionados, this powerful tool provides an unrivaled opportunity to explore  underlying principles of sorting algorithms.",
    FILE_STORAGE: "Access our comprehensive File Repository to upload and download exam papers, notes, and study materials. Organize and preserve valuable educational resources, creating a central hub for seamless file storage and retrieval. Collaborate with fellow learners and educators to build a repository of knowledge for a fruitful academic journey.",
    PRIME_NUMBER_ALGO_TEXT: "Explore the beauty of prime numbers at your own pace by setting your desired number range. Observe as the algorithm diligently identifies prime numbers within the specified range, providing you with a clear and interactive visualization of its workings. Uncover the patterns and marvel at the magic of prime numbers with our customizable and informative tool.",
    BST_ALGO_TEXT:"Experience the elegance of a Binary Search Tree Visualizer - an interactive tool to observe nodes being inserted, organized, and searched in a hierarchical structure. Explore the efficiency and simplicity of this essential data structure for maintaining sorted data.",
}

export { DescriptionEnum };